# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondJob
    steps:
    - bash: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployFirstJob
    steps:
    - bash: echo DevDeploy First Job
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployFirstJob
    steps:
    - bash: echo QADeploy First Job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployFirstJob
    steps:
    - bash: echo ProdDeploy First Job